Migrate readme yaml
cloudposse/atom-markdown-image-assistant pull request #1
Opened 2018-07-06 12:28 UTC by vadim-hleif

## what
* Add `README.yaml`

## why
* Standardize README

2018-07-06 12:40 UTC, vadim-hleif commented
depends on https://github.com/cloudposse/build-harness/issues/72

2018-07-13 20:19 UTC, osterman commented on README.yaml
> +  - name: "Rob \\| Labs"
Remvoe the `\\|` =)

2018-07-13 20:19 UTC, osterman commented on README.yaml
> +
Add a `references` section with a link to the original repo

2018-07-13 20:20 UTC, osterman commented on README.yaml
> +
Add a `copyrights` section with attribution for original author

2018-07-13 20:20 UTC, osterman requested changes
See inline comments

2018-07-17 09:24 UTC, vadim-gleyf commented on README.yaml
> +  - name: "Rob \\| Labs"
This character breaks down the table markdown.

2021-10-20 16:03 UTC, closed without merging